// Auto-generated by scrape.py — do not edit manually
const ITEMS = [
  {
    "title": "A House for Hermit Crab: Miniature Edition",
    "asin": "0887081681",
    "image": "https://m.media-amazon.com/images/I/51mYM55R0RL._SS220_.jpg",
    "price": "R$ 48,85",
    "affiliate_url": "https://www.amazon.com.br/dp/0887081681/?tag=guilhermefsp-20"
  },
  {
    "title": "Em inglês : Primeiras palavras",
    "asin": "1474918077",
    "image": "https://m.media-amazon.com/images/I/511eT-Asv3L._SS220_.jpg",
    "price": "R$ 65,38",
    "affiliate_url": "https://www.amazon.com.br/dp/1474918077/?tag=guilhermefsp-20"
  },
  {
    "title": "A grande caixa de livrinhos do bebê",
    "asin": "857406890X",
    "image": "https://m.media-amazon.com/images/I/61dKoHQvYGL._SS220_.jpg",
    "price": "R$ 73,92",
    "affiliate_url": "https://www.amazon.com.br/dp/857406890X/?tag=guilhermefsp-20"
  },
  {
    "title": "My First Root Children",
    "asin": "1782507086",
    "image": "https://m.media-amazon.com/images/I/512wOHNQ6FL._SS220_.jpg",
    "price": "R$ 48,69",
    "affiliate_url": "https://www.amazon.com.br/dp/1782507086/?tag=guilhermefsp-20"
  },
  {
    "title": "Emily Winfield Martin's Dreamers Board Boxed Set: Dream Animals; Day Dreamers",
    "asin": "1524714437",
    "image": "https://m.media-amazon.com/images/I/51juDxIxDIL._SS220_.jpg",
    "price": "R$ 114,40",
    "affiliate_url": "https://www.amazon.com.br/dp/1524714437/?tag=guilhermefsp-20"
  },
  {
    "title": "Eek! Halloween!",
    "asin": "1665925140",
    "image": "https://m.media-amazon.com/images/I/41M8nHUDBUL._SS220_.jpg",
    "price": "R$ 50,48",
    "affiliate_url": "https://www.amazon.com.br/dp/1665925140/?tag=guilhermefsp-20"
  },
  {
    "title": "Doggies: A Counting and Barking Book",
    "asin": "0671493183",
    "image": "https://m.media-amazon.com/images/I/51iTjlOM99L._SS220_.jpg",
    "price": "R$ 61,70",
    "affiliate_url": "https://www.amazon.com.br/dp/0671493183/?tag=guilhermefsp-20"
  },
  {
    "title": "Night-Night, Little Pookie",
    "asin": "1481497715",
    "image": "https://m.media-amazon.com/images/I/41G-33BkF6L._SS220_.jpg",
    "price": "R$ 35,19",
    "affiliate_url": "https://www.amazon.com.br/dp/1481497715/?tag=guilhermefsp-20"
  },
  {
    "title": "Toc... toc... Quem mora aqui?",
    "asin": "8516098540",
    "image": "https://m.media-amazon.com/images/I/51AoiUMIG-L._SS220_.jpg",
    "price": "R$ 54,85",
    "affiliate_url": "https://www.amazon.com.br/dp/8516098540/?tag=guilhermefsp-20"
  },
  {
    "title": "Aniversário da vaca Mimosa: 0",
    "asin": "856431133X",
    "image": "https://m.media-amazon.com/images/I/51A0V3XEIiL._SS220_.jpg",
    "price": "R$ 57,50",
    "affiliate_url": "https://www.amazon.com.br/dp/856431133X/?tag=guilhermefsp-20"
  },
  {
    "title": "The Very Hungry Caterpillar Eats Breakfast: A Counting Book",
    "asin": "0593226933",
    "image": "https://m.media-amazon.com/images/I/51HMpp9yqmL._SS220_.jpg",
    "price": "R$ 48,80",
    "affiliate_url": "https://www.amazon.com.br/dp/0593226933/?tag=guilhermefsp-20"
  },
  {
    "title": "Silêncio",
    "asin": "6589642192",
    "image": "https://m.media-amazon.com/images/I/41ilpQb9orL._SS220_.jpg",
    "price": "R$ 55,25",
    "affiliate_url": "https://www.amazon.com.br/dp/6589642192/?tag=guilhermefsp-20"
  },
  {
    "title": "Uma raposa: Um livro de contar (e de suspense)",
    "asin": "6581776130",
    "image": "https://m.media-amazon.com/images/I/51a7YbNf5jL._SS220_.jpg",
    "price": "R$ 50,84",
    "affiliate_url": "https://www.amazon.com.br/dp/6581776130/?tag=guilhermefsp-20"
  },
  {
    "title": "Uma planta muito faminta",
    "asin": "8574069361",
    "image": "https://m.media-amazon.com/images/I/41MxwFwvkaL._SS220_.jpg",
    "price": "R$ 49,43",
    "affiliate_url": "https://www.amazon.com.br/dp/8574069361/?tag=guilhermefsp-20"
  },
  {
    "title": "Egiptologia: Uma introdução para crianças",
    "asin": "6556973637",
    "image": "https://m.media-amazon.com/images/I/51T7FqxbzgL._SS220_.jpg",
    "price": "R$ 73,40",
    "affiliate_url": "https://www.amazon.com.br/dp/6556973637/?tag=guilhermefsp-20"
  },
  {
    "title": "Mundo: Uma introdução para crianças",
    "asin": "8578882156",
    "image": "https://m.media-amazon.com/images/I/51kyQEX4WAL._SS220_.jpg",
    "price": "R$ 68,29",
    "affiliate_url": "https://www.amazon.com.br/dp/8578882156/?tag=guilhermefsp-20"
  },
  {
    "title": "Origem",
    "asin": "6586563356",
    "image": "https://m.media-amazon.com/images/I/41t+YAqDsTL._SS220_.jpg",
    "price": "R$ 56,90",
    "affiliate_url": "https://www.amazon.com.br/dp/6586563356/?tag=guilhermefsp-20"
  },
  {
    "title": "Papai, ó!",
    "asin": "8567100526",
    "image": "https://m.media-amazon.com/images/I/41YtIkmbf8L._SS220_.jpg",
    "price": "R$ 37,64",
    "affiliate_url": "https://www.amazon.com.br/dp/8567100526/?tag=guilhermefsp-20"
  },
  {
    "title": "Cachorro quente",
    "asin": "6554851119",
    "image": "https://m.media-amazon.com/images/I/51Ls+-XkrqL._SS220_.jpg",
    "price": "R$ 46,26",
    "affiliate_url": "https://www.amazon.com.br/dp/6554851119/?tag=guilhermefsp-20"
  },
  {
    "title": "Puxa! Puxa!",
    "asin": "6556540773",
    "image": "https://m.media-amazon.com/images/I/51vo2HC7NBL._SS220_.jpg",
    "price": "R$ 46,13",
    "affiliate_url": "https://www.amazon.com.br/dp/6556540773/?tag=guilhermefsp-20"
  },
  {
    "title": "The Tale of the Castle Mice",
    "asin": "1782954015",
    "image": "https://m.media-amazon.com/images/I/61-OdzcRZCL._SS220_.jpg",
    "price": "R$ 90,45",
    "affiliate_url": "https://www.amazon.com.br/dp/1782954015/?tag=guilhermefsp-20"
  },
  {
    "title": "Da minha janela",
    "asin": "8574068748",
    "image": "https://m.media-amazon.com/images/I/61xUZM4SFDL._SS220_.jpg",
    "price": "R$ 30,92",
    "affiliate_url": "https://www.amazon.com.br/dp/8574068748/?tag=guilhermefsp-20"
  },
  {
    "title": "The A to Z of Dogs 58 Piece Puzzle: A Very Looooong Jigsaw Puzzle",
    "asin": "1913947378",
    "image": "https://m.media-amazon.com/images/I/41CnwOr5U5L._SS220_.jpg",
    "price": "",
    "affiliate_url": "https://www.amazon.com.br/dp/1913947378/?tag=guilhermefsp-20"
  },
  {
    "title": "Ted tem Tod",
    "asin": "6553845557",
    "image": "https://m.media-amazon.com/images/I/418h13D1k0L._SS220_.jpg",
    "price": "R$ 19,95",
    "affiliate_url": "https://www.amazon.com.br/dp/6553845557/?tag=guilhermefsp-20"
  }
];
